Threat modeling
TeunvdKleij/Leerlijn-SE pull request #1
Opened 2024-06-17 15:46 UTC by martijnschuman

2024-06-17 19:08 UTC, TeunvdKleij reviewed
Overal goed, twee kleine punten

2024-06-17 19:08 UTC, TeunvdKleij commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/3. Threat Model naar mitigatie.md
> +Onder REST Request en response staan de items die met REST te maken hebben.
Misschien nog een link naar REST documentatie / wat het is (misschien als item in begrippenlijst)

2024-06-20 07:42 UTC, jaelkwakkel reviewed
Paar kleine dingetjes, verder mooi 👍

2024-06-20 07:42 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/2. Wat is een Threat Model.md
> +// Voorbeeld slecht
Hoort deze nog ingevuld te worden of komt dat in een toekomstig pull-request?

2024-06-20 07:42 UTC, jaelkwakkel commented on 3. Procedurele informatie/Security/Handleiding Microsoft Threat Modeling Tool.md
> +# **Stap 5. Threat List genereren**
Het is voor mij vanuit de beschrijving niet duidelijk waarom ik zou willen exporteren naar xls. Je zou toch ook kunnen opslaan als tm7 bijvoorbeeld?

2024-06-20 08:34 UTC, TeunvdKleij reviewed
De veranderingen van rest en de "bedreiging" zijn nu goed

2024-06-20 13:09 UTC, TeunvdKleij commented
Ik ben er nog een keer doorheengegaan en ben nog een aantal punten tegen gekomen:

- In de tekst refereer je nergens naar de handleiding (met de images), misschien is dit beter dan bij pagina 3. te refereren naar stap5 van de handleiding
- Ik ziet niet de uitleg voor het genereren van het rapport (met die .htm file)
- BIj het benoemen wat wel en niet in een threatmodel hoort, lijkt het mij handig om een externe api bijv. te benoemen als een item wat wel erbij hoort, wat alleen bij "niet" neerzetten kan verwarring opleveren

2024-06-21 11:42 UTC, jaelkwakkel requested changes
Mooi de feedback verwerkt, ik zie nog wat kleine dingetjes, maar verder prima

2024-06-21 11:42 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/2. Wat is een Threat Model.md
> +title: 2. Wat is een Threat Model
Titels kunnen wel vraagtekens bevatten, dus ik denk dat met mooier is.

2024-06-21 11:42 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/2. Wat is een Threat Model.md
> +1. **Risicoanalyse**: Prioriteren van de geïdentificeerde bedreigingen op basis van hun [[2. Test#Kans|kans]] en [[2. Test#Impact|impact]].
Niet-bestaande links

2024-06-21 11:42 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/2. Wat is een Threat Model.md
> +## Begrippenlijst
Voor consistentie mooi om de begrippenlijst als volgt te maken:

```MD
> [!info]- Begrippenlijst
>- **Trust Boundary**: Grenzen binnen een systeem die verschillende niveaus van vertrouwen vertegenwoordigen.
>- **Threat Modeling**: Een proces om beveiligingsrisico's te identificeren en te mitigeren.
>-...
```

2024-06-21 11:42 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/3. Threat Model naar mitigatie.md
> +Analyseer de export en verwerk de items naar mitigaties. Een mogelijke aanpak kan zijn om de items op te splitsen in drie categorieën.
Ik denk handig om de 3 categoriën hier op een lijstje te zetten, zodat je niet hoeft te scrollen.

2024-06-21 12:36 UTC, martijnschuman commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/2. Wat is een Threat Model.md
> +1. **Risicoanalyse**: Prioriteren van de geïdentificeerde bedreigingen op basis van hun [[2. Test#Kans|kans]] en [[2. Test#Impact|impact]].
Dat klopt, deze moet straks verwijzen naar de pagina van Teun. Voor nu heb ik zijn branch even in deze gemerged zodat de link werkt, Straks moet zijn PR dus eerst naar main dat ik dan nog even kan kijken of de link het nog doet

2024-06-21 12:45 UTC, martijnschuman commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/3. Threat Model naar mitigatie.md
> +Analyseer de export en verwerk de items naar mitigaties. Een mogelijke aanpak kan zijn om de items op te splitsen in drie categorieën.
Hoe bedoel je dat precies? Gewoon een bullet list?

Dus iets als
- **HTTP Request en Response**: Onder HTTP Request and Response staan alle items die bij HTTP Request en Responses hoort.
- **Query Request en Response**: Onder Query Request en Response staan alle items die met SQL statements te maken hebben. 
- **REST Request en response**: Onder REST Request en response staan de items die met REST te maken hebben. REST staat voor REpresentational State Transfer [OWASO REST Security Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html). REST applicaties maken gebruiken HTTP-verzoeken om toegang te krijgen tot en te manipuleren van gegevens. Dit doen ze met behulp van de standaard HTTP-methoden zoals GET, POST, PUT en DELETE.

En dan de foto's, of helemaal geen foto's?

2024-06-21 13:34 UTC, JorrickHS requested changes
Ziet er mooi uit! Misschien nog even die bronnenlijst toevoegen op 3 :)

2024-06-21 13:34 UTC, JorrickHS commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/3. Threat Model naar mitigatie.md
> +Onder REST Request en response staan de items die met REST te maken hebben. REST staat voor REpresentational State Transfer [OWASO REST Security Cheat Sheet](https://cheatsheetseries.owasp.org/cheats
Misschien nog even een bronnenlijst toevoegen met deze link 🗡️

2024-06-22 15:37 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/2. Design - Threat Modelling/3. Threat Model naar mitigatie.md
> +Analyseer de export en verwerk de items naar mitigaties. Een mogelijke aanpak kan zijn om de items op te splitsen in drie categorieën.
Nee, gewoon deze zin er achter plakken: De 3 categorieën zijn HTTP, QUERY en REST.

2024-06-22 16:09 UTC, merged