Risk assessment
TeunvdKleij/Leerlijn-SE pull request #4
Opened 2024-06-20 11:22 UTC by TeunvdKleij

2024-06-20 11:30 UTC, JorrickHS requested changes
Misschien even in de begrippenlijst zetten wat materiele zaken en inmateriele onderdelen precies zijn. Voor de rest 👯 🥳

2024-06-20 11:30 UTC, JorrickHS commented on 2. Ondersteunende-informatie/Security/SSDLC/1. Requirements - Risk Assessment/1. Wat is een Risk Assessment.md
> +In latere stappen is steeds weer gekeken of de Requirements aangepast of uitgebreid moesten worden. Dan werden de stappen van Risk Assessment opnieuw doorlopen.
Requirements zonder hoofdletter?

2024-06-20 11:30 UTC, JorrickHS commented on 2. Ondersteunende-informatie/Security/SSDLC/1. Requirements - Risk Assessment/1. Wat is een Risk Assessment.md
> +Om risico’s te kunnen identificeren worden eerst de assets bepaald vanuit de vastgelegde requirements. Assets zijn hardware, software, materiële zaken en immateriële onderdelen van het systeem.
Wat zijn materiele zaken en immateriele onderdelen van het systeem? Misschien niet voor iedereen eve duidelijk

2024-06-20 12:21 UTC, jaelkwakkel requested changes
Paar kleine puntjes. Gebruik van voorbeelden is een goed idee.

2024-06-20 12:21 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/1. Requirements - Risk Assessment/1. Wat is een Risk Assessment.md
> +De grootte van het risico wordt bepaald door de kans te vermenigvuldigen met de impact:
Hoe kun je goed aangeven wat de kans is? Wanneer is een kans "groot"? Zelfde voor impact

2024-06-20 12:21 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/1. Requirements - Risk Assessment/1. Wat is een Risk Assessment.md
> +Aan de hand van de risico classificatie is bepaald welke voor welke risico’s security measurements worden genomen. De maatregelen zijn bedacht door de developers op basis van hun kennis._
Ik denk dat een concreter voorbeeld duidelijker overbrengt wat er gedaan wordt met een risico. Bijvoorbeeld:

Uit het risk assessment kwam naar voren dat er een hoge kans en impact is voor het uitvoeren van cross-site-scripting. Daarom is in het technisch ontwerp beschreven op welke manier de input van gebruikers ge-sanitized wordt.

2024-06-20 23:38 UTC, TeunvdKleij commented on 2. Ondersteunende-informatie/Security/SSDLC/1. Requirements - Risk Assessment/1. Wat is een Risk Assessment.md
> +De grootte van het risico wordt bepaald door de kans te vermenigvuldigen met de impact:
In de zin eronder stond al dat deze schatting gemaakt werd door een of meerdere stakeholders. Ik heb dit nog even uitgebreid, een zin toegevoegd voor kans en impact en een extra voorbeeld toegevoegd voor het bepalen van een impact.

2024-06-20 23:41 UTC, TeunvdKleij commented on 2. Ondersteunende-informatie/Security/SSDLC/1. Requirements - Risk Assessment/1. Wat is een Risk Assessment.md
> +Aan de hand van de risico classificatie is bepaald welke voor welke risico’s security measurements worden genomen. De maatregelen zijn bedacht door de developers op basis van hun kennis._
Goed voorbeeld, ik heb deze toegevoegd. Het helpt idd als extra verduidelijking

2024-06-21 11:30 UTC, jaelkwakkel requested changes
Prima, paar kleine wijzigingen voor consistentie maar verder mooi

2024-06-21 11:30 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/1. Requirements - Risk Assessment/1. Wat is een Risk Assessment.md
> +De volgende stappen zijn doorlopen om de requirements te verzamelen. De start van het proces is een interview met de opdrachtgever geweest. Uit dit interview zijn requirements verzameld en vastgelegd
Je zegt hier 3 stappen, maar in de afbeelding staan 4 stappen

2024-06-21 11:30 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/1. Requirements - Risk Assessment/1. Wat is een Risk Assessment.md
> +title: Wat is een Risk Assessment
Titels kunnen wel vraagtekens aan, dus ik zou deze toch wel een vraagteken geven.

2024-06-21 11:30 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/1. Requirements - Risk Assessment/1. Wat is een Risk Assessment.md
> +## Begrippenlijst
Voor consistentie met andere branches kun je de begrippenlijst als volgt maken:
```MD
> [!info]- Begrippenlijst
>- **AVG**: Algemene Verordening Gegevensbescherming
```

2024-06-21 13:10 UTC, JorrickHS approved these changes
goed werk

2024-06-21 13:41 UTC, martijnschuman commented
Misschien kan je nog even kijken naar de witregels, is nu naar mijn mening wel beetje veel

![image](https://github.com/TeunvdKleij/Leerlijn-SE/assets/31829786/d0f5e4dd-9840-49d4-a16b-b33e707a5e7e)

2024-06-22 16:12 UTC, merged