Eerste versie Setup Skylab
TeunvdKleij/Leerlijn-SE pull request #5
Opened 2024-06-20 22:27 UTC by JorrickHS

Ben benieuwd wat jullie vinden. Beetje ingewikkeld aangezien het minder op een workshop lijkt als bv thread modelling of risk assessment.

Hoor graag wat jullie vinden en wat er verbeterd kan worden. Ik heb nog 1 uur en 23 minuten ☯️

2024-06-20 22:36 UTC, martijnschuman requested changes
Je kan misschien nog even kijken of je een verwijzing naar andere dingen zoals STRIDE kan maken. Je zou eventueel nog kunnen toelichten waarom Debian en niet Ubuntu en daar een vergelijking tussen maken. Ubuntu is ook een veel gekozen alternatief.

2024-06-20 22:36 UTC, martijnschuman commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +In de Skylab-workshop wordt in zes opdrachten uitgelegd hoe je met drie verschillende machines op Skylab een DTAP-buildstraat kunt opzetten. Hier worden extra details verschaft die je goed zou kunnen
Staat twee zinnen hierboven ook al

2024-06-20 22:36 UTC, martijnschuman commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +In de Workshop Skylab wordt in zes opdrachten uitgelegd hoe je met drie verschillende machines op Skylab een DTAP-buildstraat kunt opzetten. Deze workshop biedt extra informatie die nuttig is voor je
Niet alleen portfolio maar ook voor ervaring met opzetten van webserver etc. Kan je misschien nog op een manier verwerken

2024-06-20 22:36 UTC, martijnschuman commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +	De Debian 12 serverhost fungeert als de centrale server voor de buildstraat. Debian 12 is gekozen vanwege zijn stabiliteit, veiligheid en uitgebreide ondersteuning. Op deze server worden verschillen
Misschien kan je bij de systement van stabiliteit, veiligheid etc nog een bron toevoegen

2024-06-20 23:20 UTC, TeunvdKleij reviewed
Lekker gewerkt Jorrick

2024-06-20 23:20 UTC, TeunvdKleij commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +In de Workshop Skylab wordt in zes opdrachten uitgelegd hoe je met drie verschillende machines op Skylab een DTAP-buildstraat kunt opzetten. Deze workshop biedt extra informatie die nuttig is voor je
Ben ik mee eens, het is inderdaad ook een algemene leerervaring voor een student

2024-06-20 23:20 UTC, TeunvdKleij commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +	De Debian 12 serverhost fungeert als de centrale server voor de buildstraat. Debian 12 is gekozen vanwege zijn stabiliteit, veiligheid en uitgebreide ondersteuning. Op deze server worden verschillen
Ja een bron en misschien in een zin kort welke stabiliteit, veiligheid en ondersteuning

2024-06-20 23:20 UTC, TeunvdKleij commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +	SSH versleutelt alle gegevens die tussen je lokale machine en Debian 12 server worden verzonden, hierdoor wordt je beschermd voor bijvoorbeeld een man-in-the-middle aanval. Hierdoor is het beheren v
"SSH versleutelt alle gegevens die tussen je lokale machine en Debian 12 server worden verzonden. Hierdoor word je beschermd..."

2024-06-20 23:20 UTC, TeunvdKleij commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +## Begrippenlijst
Misschien hier nog de CLI aan toevoegen

2024-06-20 23:29 UTC, JorrickHS commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +## Begrippenlijst
Ik benoem de CLI al onder het 2. Toegang deel, lijkt me voldoende toch?

2024-06-21 11:23 UTC, jaelkwakkel requested changes
Mooi werk 👍 Paar puntjes voor verbetering. Ik zou voor de zekerheid ook nog een keer spelling en grammatica checken.

2024-06-21 11:23 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +In de eerste opdracht van de Workshop Skylab worden er die machine aangevraagd op het Skylab service van Windesheim. Hier wordt uitgelegd wat deze machines doen en waarom er voor deze machines gekoze
drie machines*

2024-06-21 11:23 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/2. Deployment op Skylab.md
>  - Wat is certbot
Moet deze TODO-lijst nog weg?

2024-06-21 11:23 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/2. Deployment op Skylab.md
> +Een connection string is als een adres voor je database. Het vertelt je applicatie waar de database is, hoe je er verbinding mee maakt en welke inloggegevens je moet gebruiken. verschillende database
bereiken* 
Misschien een goed idee om de basiselementen van een connection string ook uit te leggen?

2024-06-21 11:23 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/2. Deployment op Skylab.md
> +Tip: sla je database inlog gegevens op in een envirement variable, zodat deze niet los tussen je code staat.
Environment*

2024-06-21 11:23 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/2. Deployment op Skylab.md
> +Bij opdracht 4 van de workshop ga je apache installeren. Apache is een web server die in dit geval word gebruikt als een reverse proxy. Een proxy(ofwel forward proxy) staat tussen een client en het i
Ik denk dat een diagram veel kan helpen bij het uitleggen van het verschil tussen forward proxy en reverse proxy. Vanuit deze uitleg begrijp ik het verschil nog niet volledig. Je kunt even in de ZAP workshop kijken, daar wordt ook iets over proxies beschreven.

2024-06-21 11:23 UTC, jaelkwakkel commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +	Daarnaast kan in een later stadium van het schrijven van het portfolio dezelfde Kali Linux-host gebruikt worden om de Workshop ZAP uit te voeren.
Misschien interessant om dieper in te gaan op de Kali als pentesting/security testing tool?

https://www.hackerone.com/knowledge-center/7-pentesting-tools-you-must-know-about#:~:text=Penetration%20Testing%20Experts-,1.%20Kali%20Linux,-License%3A%20open%20source

2024-06-21 11:57 UTC, JorrickHS commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/2. Deployment op Skylab.md
>  - Wat is certbot
Yep eigenlijk hoort deployment nog niet in deze merge te zitten, foutje in de commit.

2024-06-21 14:09 UTC, martijnschuman requested changes

2024-06-21 14:09 UTC, martijnschuman commented on 2. Ondersteunende-informatie/Security/SSDLC/5. Deployment - Deployment op Skylab/1. Setup Skylab.md
> +Om de veiligheid van de buildstraat verder te bevorderen wordt er in de 4e opdracht van de Workshop Skylab een SSH geconfigureerd. De risico's die SSH voorkomt kan teruggekoppeld worden aan het STRID
Misschien kan je hier nog een verwijzing maken naar de pagina van threat modeling. Dan wordt de linker sneller / makkelijker met elkaar gelegd. Denk dat je het beste de threat modeling branch dan even in deze branch kan mergen zodat je hem gelijk naar de juiste pagina kan linken

2024-06-22 16:12 UTC, merged